### ISSUE TITLE
ObjLoad/ObjDump 的实现方案

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#10]
大佬，ObjLoad / ObjDump 能用 python 也能解析的数据格式进行序列/反序列吗？比如使用 Protobuf 或者 FlatBuffers，只要 python能识别的二进制格式都可以。
当前是使用的内置的 json，但我更想用ObjLoad / ObjDump，但数据 py 无法解析。

**Comment by thqby** [comment]
不能
当前的objdump比json要慢

**Comment by Frozen1084** [comment]
是的，objdump 比 json 要慢，我虽然不懂C，但看了源码也感觉效率不高。
但这似乎是因为 objdump 的数据格式是未经优化的，
而Protobuf 或者 FlatBuffers，效率都远高于json，只是不知道与ahk的map/arr对接后是不是同样优秀。

https://blog.csdn.net/qq_15807167/article/details/53575510
