### ISSUE TITLE
热键经常失效或错误触发

### ISSUE THREAD

**Issue by Blue-Savage** [thqby/AutoHotkey_H#14]
我最近才开始使用这个版本，话说是不是应该起个有别于H/L的名字？遇到的问题除了崩溃，就是热键频繁失效，或者错误地触发。

这些问题是在 HotKeyIt 推出新 NewThread() 时也存在的，因为那时所有不同线程的热键都使用同一个热键系统，在一个线程注册一个热键，在另外一个线程再次注册会报错。还有热字符串等一堆问题。
这些都是 HotKeyIt 已经解决了的，热键从那时到现在都是正常的。是不是某些改动你没有合并？

暂时没有找到完全复现的方法，就不贴代码了。

**Comment by miozus** [comment]
你的系统版本？

我的 Windows11 ，之前遇到过一个 bug

 《钩子一分钟自动失效问题》

发到英文论坛也没有解决。

https://www.autohotkey.com/boards/viewtopic.php?f=76&t=96587

我的解决方案：

1) caps up：附带检查大写情况，改成小写

2) 钩子未按预期停用时，手动重载脚本

**Comment by Blue-Savage** [comment]
我用 WIN10。如果问题仍未解决，可以抛开 AHK 热键，自己用WINAPI 重构，看看是否正常。

**Comment by thqby** [comment]
为了便于维护，当前的合并策略是冲突部分以L版为主，明确知道原因的部分保留

**Comment by Blue-Savage** [comment]
从#11 来看，这个版本的用户很少使用热键，不然这么基础性的问题不会到现在才有反馈。
ahk 热键并不适用当前的多线程环境，而 HotKeyIt 已经对此进行了修复和改进。
所以这个"明确知道原因"的情况不需要合并？

**Comment by thqby** [comment]
又检查一遍，该合并的都合并了，多线程相同热字串同时触发没合并。
beta1到beta6热键部分有更新不知道有没有影响。
热键用的不多，没复现代码的话不好找bug。

**Comment by Blue-Savage** [comment]
之前我是用 HotKeyIt 版 DLL 加载热键，这几天改回了此版，一直没遇到错误。
