### ISSUE TITLE
MsgBox() 第一个参数支持对象

### ISSUE THREAD

**Issue by fir05** [thqby/AutoHotkey_H#15]
是否可以让 MsgBox() 第一个参数支持对象？
增加一个判断，如果是对象则用 JSON.Stringify(text, 4) 解析。
MsgBox() 不是那种对性能有需求的函数，增加一个判断应该不会造成多少负面影响。

**Comment by thqby** [comment]
调试器有输出完整对象的方法，比msgbox更好用

**Comment by fir05** [comment]
冒昧一问，你们都是用调试器代替MsgBox？在我看来这完全是两个东西啊。

**Comment by thqby** [comment]
![image](https://user-images.githubusercontent.com/28240311/177258702-7945126e-df24-4c7a-a005-0149e2364696.png)
像这样

**Comment by fir05** [comment]
我知道调试器可以查看对象内容。
大多数用户是不用调试器的，用记事本或者那些老式编辑器写ahk的也大有人在。
用MsgBox显示一个变量内容，并不等于调试场景。
