### ISSUE TITLE
编译文件使用独立仓库

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#19]
能否在独立仓库发布编译文件？便于用脚本自动更新。谢谢。

**Comment by thqby** [comment]
https://github.com/AutoHotkey/AutoHotkeyUX/blob/main/inc/GetGitHubReleaseAssetURL.ahk

也可以从release中获取

**Comment by Frozen1084** [comment]
因为是7z文件包，里面32位文件我也用不到，使用 API 也不能按需下载。
或者不如将 64/32 单独打包成7z发布，这样可以吗？

**Comment by thqby** [comment]
在脚本里加上解压删除不就好了

**Comment by Frozen1084** [comment]
> 在脚本里加上解压删除不就好了

这样用脚本更新还是很麻烦。
比如你刚刚更新了7Z包，但用API获取的版本还是"beta.7"，唯一可用的匹配数据就是上传时间。可我只有AutoHotkey.exe的修改时间，也不能和它匹配。
我的解决方法，不管是否更新，先将7Z包下载解压，计算AutoHotkey.exe的MD5是否与本地一致，不一致就更新。
你不觉得这很麻烦吗？

能不能给AutoHotkey.exe设置个纯数字的版本号？方便比对。

H的原版 是将所有文件 HASH 值写入到文件的
https://github.com/HotKeyIt/ahkdll-v2-release/blob/master/HASH

**Comment by thqby** [comment]
https://api.github.com/repos/thqby/AutoHotkey_H/releases/latest

本地记录下更新时的`updated_at`字段，也可以将这个时间设置到exe就不需要额外文件`FileSetTime()`，再比较下就行了

**Comment by Frozen1084** [comment]
1，我打开github很慢还时断时续。压缩包里的32位文件，根本用不到，下载它是浪费时间，甚至有时只需要下载exe文件，下载整个包更加浪费。
2，updated_at 字段，保存到本地的话，复制exe时还要复制这个记录文件。
设想一个初用这个版本的新手，他根本没有旧updated_at数据

所以能不能
1，64/32 分开打包。
2，EXE使用一个数字版本号(哪怕是commits号)，并加在文件名里(beta.7-2333.7z )。H是有版本号的(2.0-beta3-H001)
