### ISSUE TITLE
B10 的两个问题

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#22]
1，能恢复H版 OnMessage 函数的第二个参数窗口句柄吗？
2，能让 addScript 所加载代码的报错与 L 版保持一致吗？比如下面的错误，至少要贴出是发生在哪个函数。

```
*THREAD9180?00000222C43200AA#52652.AHK
---------------------------
Too many parameters passed to function.
---------------------------
```

**Comment by thqby** [comment]
第一个感觉作用不大，在监听消息比较多的时候会损失点性能

第二个调用栈信息里不是有函数名吗

**Comment by Frozen1084** [comment]
1在多窗口时还是蛮有用的，特别是不同作用的窗口，比如响应贴边隐藏的窗口，和普通窗口同时存在，就必须在回调函数再做一次判断。为每个窗口设置单独的监听，很有用的啊。

我解决2的问题的了。需要EXE文件的对话框资源文件。这个不是AHKDLL的锅，需要调用它的软件自己解决。

**Comment by Frozen1084** [comment]
顺便一提。我尝试用WVS 2022编译，全选生成，没有一个是成功的。
主要错误是这两个：
```
LNK1104	无法打开文件“source/lib_mpir/Win64/mpir.lib”
D:\AutoHotkey_H-alpha\source\AutoHotkey.cpp(31,10): fatal  error C1083: 无法打开包括文件: “vld.h”: No such file or directory
```

**Comment by thqby** [comment]
这两个还没上传
第一个可以在config.h里禁用
下一个只在debug中使用，网上下载安装的

**Comment by thqby** [comment]
2修改一个参数就可以解决

**Comment by Frozen1084** [comment]
我不会C，编译也是按照论坛上的教程来操作的，debug应该也用不到。
我查看了conflg.h，但没找到"mpir"相关的东西，请问要怎么禁用？

-----


呃能否顺便请教个vscode-autohotkey2-lsp 相关的问题。。。

vsc是默认对函数内或者花括号内的代码缩进的，但 ahk 自运行的主代码是无法缩进的，我研究了很久也没找到选项。
没有缩进，代码和边框挤在一起，导致用鼠标点击行首时，经常点不准确，不是点到边框，就是没点到行首。
所以请问有办法对非花括号内的代码也进行缩进吗？或者说全局缩进。

**Comment by thqby** [comment]
最后面ENABLE_DECIMAL

alt+shift+f代码格式化没用过？
或者你指的是formatOnType

**Comment by Frozen1084** [comment]
图1是当前格式化的结果。就像我说的，代码和边框之间没有空隙。
![avatar](https://i.imgur.com/I4IOsIx.png)

图2是我希望的样式
![avatar](https://i.imgur.com/ZsT8jGi.png)

**Comment by Frozen1084** [comment]
谢谢。MT_Release成功编译了。

Release也编译成功了，不过MT的1.7M，Release版本的才1.2M，是经过压缩了吗？我测试了下，正常使用。

**Comment by thqby** [comment]
第一行缩进再格式化

没mt的要装vc运行时

**Comment by Frozen1084** [comment]
了解了，谢谢。

**Comment by thqby** [comment]
> 1，能恢复H版 OnMessage 函数的第二个参数窗口句柄吗？

```
Gui().OnMessage((wp,lp,msg,hwnd)=>0)
```

**Comment by jollycoder** [comment]
Hi, [thqby](https://github.com/thqby)
I tried to compile AHK_H, but encountered the error mentioned above:
LNK1104	无法打开文件“source/lib_mpir/Win64/mpir.lib”
I commented out ENABLE_DECIMAL in conflg.h, but it caused other errors. What sould I do?
