### ISSUE TITLE
DLL窗口的任务栏图标

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#25]
非ahk调用 dll ，MsgBox窗口，其任务栏按钮没有ahk图标。ahk.exe 有。
这是否与 dll 报错窗口的问题类似？

![avatar](https://i.imgur.com/oHAKIOl.png)

**Comment by thqby** [comment]
由启动exe的主图标决定的，dll的错误框应该可以正常显示了

**Comment by Frozen1084** [comment]
谢谢
