### ISSUE TITLE
B15的两个问题

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#31]
都是在B13正常的代码。

1.
```
Error: Invalid option.

Specifically: Caption
▶  001: Gui("-Caption +AlwaysOnTop")
       002: Exit

```

2. 这个绘制字符串的脚本没报错，但只绘制大概100宽度的字符，怎么调整参数都没用。

**Comment by thqby** [comment]
l版b15的bug?

**Comment by thqby** [comment]
2. `.show()`设置宽度, 这处 https://github.com/Lexikos/AutoHotkey_L/commit/3ddc4e150546c6f439ada5f715c39801e49e1c9c 变更导致需要手动设置界面大小

**Comment by Frozen1084** [comment]
谢谢!
