### ISSUE TITLE
加载 ahk.exe 调用 NewThread() 崩溃

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#33]
我尝试用 ahk.exe 代替 dll，LoadLibrary() 和 GetProcAddress("NewThread") 都正常。但一调用 NewThread() 就崩溃，能修复这一崩溃吗？

之所以想用ahkexe来代替ahkdll，是因为二者功能几乎相同，而且不知道为啥dll的体积比exe还要大，只用exe的话，能够减少软件包一半的体积。

**Comment by thqby** [comment]
ahk.exe不能代替dll来使用, exe是固定基址的, dll是动态基址的。 另外dll多个com组件功能, 可以注册后通过com对象启动。
