### ISSUE TITLE
OnMessage by Hwnd for Controls

### ISSUE THREAD

**Issue by Clamsoda** [thqby/AutoHotkey_H#37]
Would you consider expanding Gui.Prototype.OnMessage(EventName, Callback [, AddRemove]) to the controls prototype as well?

Currently, AHK_H v2.0.2 throws:
Error: This value of type "Gui.Edit" has no method named "OnMessage".

**Comment by thqby** [comment]
I think OnMessage works with Windows, so it doesn't need to be added to the control class.

Will function `OnMessage(msg, function)` receive a message with a handle to the control?

**Comment by Clamsoda** [comment]
Yes, the AHK_L implementation of OnMessage(msg, function) returns wParam, lParam, hwnd, and msg.

The handle could be for a window OR a control.

My interpretation of HotKeyIt's implementation of OnMessage(msg, HWND, ...) was a convenience/performance feature to get rid of the need for a guard clause in the call back function to match the desired window/control hwnd.
See: https://hotkeyit.github.io/v2/docs/commands/OnMessage.htm

Your change overview claims you changed HotKeyIt's OnMessage(...) implementation with something more inline with AHK_Lv2's object oriented approach, which I think is nice.

The issue I have is that the implementation is only valid for windows, and not for controls.  HotKeyIt's implementation would work for either windows OR controls.

This means that I still need to filter the hwnd in the callback function with a guard clause for messages related to controls.

**Comment by thqby** [comment]
I see. It should be in the near future.

**Comment by thqby** [comment]
Do you know what kind of message the control will receive?

**Comment by Clamsoda** [comment]
It could be any message.

In my particular example, I am manipulating LBUTTONDOWN, RBUTTONDOWN, and KEYDOWN.  Here is my implementation if it helps clarify my situation and what I was hoping to achieve.

```
OnMessage(0x0201, KillMainEdit) ; WM_LBUTTONDOWN
OnMessage(0x0204, KillMainEdit) ; WM_RBUTTONDOWN
OnMessage(0x0100, KillMainEdit) ; WM_KEYDOWN
KillMainEdit(wParam, lParam, msg, hwnd) {
	Global

	if ( hwnd = TerminalGUI["MainEdit"].hwnd )
		if (A_TickCount - KILL_MAIN_EDIT < 250 )
			Return 0
}
```

Notice the guard clause "if ( hwnd = TerminalGUI["MainEdit"].hwnd )".  This is what I was hoping/thought the HWND specific implementation of OnMessage() would prevent.  Message 0x0201 dispatches the callback KillMainEdit() EVERY single time WM_LBUTTONDOWN is received, and it is up to me to filter out who called it by HWND.

Edit:
Every single control in my window, and the window ITSELF generates WM_LBUTTONDOWN, so the callback is dispatched every single time the user uses the left mouse button.

**Comment by thqby** [comment]
I was concerned that the extra retrieval action would slow down message processing.
Currently, the main loop only retrieves the parent gui object when msg>= WM_KEYFIRST && msg<= WM_KEYLAST.

**Comment by thqby** [comment]
It has been released.
