### ISSUE TITLE
Error failed to open the file "source/lib_mpir/Win64/mpir.lib"

### ISSUE THREAD

**Issue by jollycoder** [thqby/AutoHotkey_H#38]
Hi, [thqby](https://github.com/thqby)
I tried to compile AHK_H, but encountered the error mentioned [here](https://github.com/thqby/AutoHotkey_H/issues/22#issuecomment-1277023170):
LNK1104 failed to open the file "source/lib_mpir/Win64/mpir.lib"
I commented out ENABLE_DECIMAL in conflg.h, but it caused other errors. What should I do?

**Comment by thqby** [comment]
https://github.com/thqby/AutoHotkey_H/releases/tag/lib_mpir

**Comment by jollycoder** [comment]
Thanks, I'll try.

**Comment by jollycoder** [comment]
Everything worked out! Thank you!
