### ISSUE TITLE
从字符串序列化 ahk 对象

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#39]
我在V1时写过一个解析ini到对象的库，类似这种

```
[info]
var_test = {path: a_ahkdir "\test.exe", data: map(), id: Random(1,10), from: "t"}
call_ToolTip_param = [,,,1]
```

这真的是种非常高效的配置格式，可惜转V2时我嫌重写太麻烦就弃用了。
好在json内置了，用起来很方便，但有些问题却无法解决。
比如"[,,,1]" 就无法通过json转化为 ToolTip可用的参数。
而显然"[,,,1] "是符合ahk对象的创建规则的。

那么能否添加一个类似 json() 的序列化ahk对象规则字符串的新方法呢？
解析这些规则的方法，在底层是存在的。
我也尝试通过 addScript/ahkExec，但感觉效率不高，且容易出错。序列化出错和addScript出错，是两个性质。
序列化的过程虽然会调用函数和变量，但不会创建函数和变量。用 addScript 有点浪费。
如果将AutoHotkey底层解析代码创建对象的方法拿出来作为一个序列化工具，那就完美了。

```
 var_test := ahkcreate( '{path: a_ahkdir "\test.exe", data: map(), id: Random(1,10), from: "t"}' )

**Comment by thqby** [comment]
ahk对象解析代码是混在一起的，不能独立出来使用，远复杂于json的解析器，要支持上面类型的表达式目前只有ahkexec

**Comment by Frozen1084** [comment]
谢谢，ahkExec 有优化的可能吗？ahkExec 调用一次大概耗时350微秒，1000次用了25毫秒。

```
loop 1000
ahkExec 'A_Args.tt' a_index ':={path: a_ahkdir "\test.exe",  id: Random(1,10), from: "t"}`n'
```
