### ISSUE TITLE
JSON 中用 unset 代替 null

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#40]
AutoHotkey 并没有 null  定义，能否用 unset 代替呢？

这样用 json 传输某些必须忽略的函数参数就简单了，比如 PostMessage() 的控件参数通常会被忽略，现在可以这样写了
```
[1173, 40, 0, null, "ahk_class Test"]
```

而 isset() 和 ?? 都能很好的对 null 进行判断。

**Comment by thqby** [comment]
unset在Map和Object中表现为没有这个键值对，会出现不可逆转换
isset()和??都只能对变量使用isset(obj['val'])这样是无效的

**Comment by Frozen1084** [comment]
JSON.Stringify([1,,3]) 会转换json为 [1, null, 3]
那么  [1, null, 3] 转换为 [1,,3] 应该也是合理的吧

====

这么说对象缺少个类似isset()的方法。
t:=[1,2,3]
t.delete(2)
这种情况下 t[2] 就是 unset

**Comment by thqby** [comment]
已实现
