### ISSUE TITLE
兼容json格式的对象创建

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#42]
从V1切换到V2，最痛苦之处莫过于无法使用json格式创建对象了。
原来复制粘贴就能完成的脚本现在必须手动修改。而且创建的map()对象真的难以阅读，连续的逗号，丧失了分明的结构。

var := {"name": "test"} 会报错。
但为何不能更加智能些，判断""包裹的内容是否可以作为键？
这会引发什么不好的事情吗？
在name可以作为键使用的情况下报错，毫无必要啊，感觉只是为了证明V2的严谨。

希望可以兼容被引号包裹的键，当包裹的内容无法作为键时才报错。

---

比如 我让ChatGPT推荐了一些新闻网站。在V1这是可以直接使用的。但在V2，我需要将它放在JSON.Parse()里转换一次，或者每次调用时都转换一次。

[
  {
    "name": "TechCrunch",
    "url": "https://techcrunch.com/"
  },
  {
    "name": "Wired",
    "url": "https://www.wired.com/category/business/"
  },
  {
    "name": "The Verge",
    "url": "https://www.theverge.com/tech"
  }
]

-----

这么说能在JSON添加一个将json转换为ahk代码的方法吗？

t := JSON.Parse('{"name": "test"} ')

JSON.Script(t) ; => map("name", "test")

**Comment by thqby** [comment]
JSON.Parse('{"name": "test"}',,0) ; {name: "test"}

**Comment by Frozen1084** [comment]
谢谢，但你的回复跟帖子涉及的两个问题都没有关系啊。
objkey 支持 ""。极大便利的同时没有想到会有什么负面影响。
将json格式转换为AutoHotkey格式

你的意思是每次运行都转换一次json格式吗？
