### ISSUE TITLE
支持对象的树状读写

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#43]
能支持对象的树状读写吗？
这个特性同样是在V1超好用，V2丢失。
t := { a: { b: { c: : 3 } } }
var := t["a", "b", "c"]
t["a", "b", "c"] := 4

我思索了"[]"在V2的使用场景，似乎只有 array()创建一个场景。
无论是 arr := [1,2,3]
或者  test([1,2,3] *)
都与 t["a", "b", "c"] 这种树状读写结构有明显差别。

树状读写真的很实用，我当前用自定义函数实现，但总感觉性能不行，而且用函数也显得不简洁。

谢谢添加对象引号键的支持，太好用了。

**Comment by thqby** [comment]
上述情况还是`t.a.b.c`更简洁

**Comment by Frozen1084** [comment]
简洁是简洁，问题是不兼容 array和map。这种多层对象通常都是json，通常混合着array map。
