### ISSUE TITLE
编译后产生奇怪的错误

### ISSUE THREAD

**Issue by vvyoko** [thqby/AutoHotkey_H#44]
目录结构是这样的
```
D:\test\ahk.ahk
D:\test\ahk.exe
D:\test\test.txt
```

测试代码是这样的,这里是简化了的,原本需求是为了运行上级目录的指定程序
```
loop files A_ScriptDir '\test.txt'
    path := A_LoopFileFullPath

MsgBox(path)
```

原版任何情况都正常
H版未编译前正常,编译后某些情况出现了这种报错
![20230321162912](https://user-images.githubusercontent.com/2145741/226552674-f5e03170-7a9c-4013-98b9-f9859e7ffbb2.jpeg)

```
;测试正常的
D:\test\ahk.exe "D:\test\ahk.exe"
D:\test\ahk.exe "D:\test1\ahk.exe"
D:\test\ahk.ahk "D:\新建文本文档.txt"

;测试出错的
D:\test\ahk.exe "D:\新建文本文档.txt"
```

**Comment by thqby** [comment]
![image](https://user-images.githubusercontent.com/28240311/226614392-6aa9eee5-68a1-4a54-aff8-8fe6f8a8412b.png)
未发现错误

上图看着ahk.exe像是未编译的，txt里才是脚本，A_ScriptDir 则是 D:

**Comment by vvyoko** [comment]
> ![image](https://user-images.githubusercontent.com/28240311/226614392-6aa9eee5-68a1-4a54-aff8-8fe6f8a8412b.png) 未发现错误
> 
> 上图看着ahk.exe像是未编译的，txt里才是脚本，A_ScriptDir 则是 D:

上传了我使用的所有东西
包括刚重新下载的Ahk2Exe及AutoHotkey64
在1级目录增加了一个`测试`的脚本防止我手动输入出错

[测试.zip](https://github.com/thqby/AutoHotkey_H/files/11029383/default.zip)



![动画](https://user-images.githubusercontent.com/2145741/226638968-917d906c-d4ea-4fd7-bccd-8f0bd6da1299.gif)

**Comment by thqby** [comment]
打开后没有`新建文本文档.txt`这个弹窗
