### ISSUE TITLE
ReleaseDll 无法编译

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#45]
错误	RC2135	file not found: temp\x64\MT_ReleaseDll\AutoHotkeyx.tlb

另外一个错误是：
LINK : error C2220: 以下警告被视为错误
LINK : warning C4727: 具有相同时间戳的名为 z:\autohotkey_h-alpha\temp\x64\release\autohotkey64.pch 的 PCH 已存在于 z:\autohotkey_h-alpha\temp\x64\release\pch_min.obj 和 z:\autohotkey_h-alpha\temp\x64\release\pch.obj 中。 使用第一个 PCH。

**Comment by thqby** [comment]
从temp\x64\ReleaseDll\AutoHotkeyx.tlb复制到temp\x64\MT_ReleaseDll\AutoHotkeyx.tlb

releasedll对应的是\releasedll\autohotkey64.pch吧

**Comment by Frozen1084** [comment]
我当时就复制了，然后是更多的文件缺失错误

**Comment by thqby** [comment]
缺什么

**Comment by Frozen1084** [comment]
好像缺少Debug目录中的文件。你编译次试试呗，手动复制文件本来就是多余的，就没必要追究这些次生错误了。

**Comment by thqby** [comment]
vld.h? 网上下的，不需要可以去掉

一般我只是编译的`Debug`和`MT_Release(Dll)`

**Comment by Frozen1084** [comment]
那就删除那些不支持的类型呗，不断试错后才不得不去编译MT版本，是没必要的过程。

**Comment by thqby** [comment]
已更新配置文件，根据某些文件是否存在，启用或禁用相关功能
