### ISSUE TITLE
SetTimer 支持函数名参数

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#46]
V2使用SetTimer动态调用函数，或者从其他H线程调用SetTimer都变得非常麻烦。我不得不重新包装它：

timer2(fn,time){
if isset(%fn%)  && %fn% is func
SetTimer %fn%, integer(time)
}

所以，能恢复对函数名字符串的支持吗？也就是兼容V1，这不会破坏当前的V2规则。

**Comment by thqby** [comment]
try SetTimer %fn%, integer(time)

**Comment by Frozen1084** [comment]
这里动态调用的是%"SetTimer"%，不是它的参数。
dll.ahkFunction("SetTimer","test", "1000")

for n in [["MsgBox","abc"], ["SetTimer","test","0"]]
%n. RemoveAt(1)%(n*)
