### ISSUE TITLE
Error When Passing Array Between Threads

### ISSUE THREAD

**Issue by Clamsoda** [thqby/AutoHotkey_H#47]
Error: (0x80020009) Exception occurred.
Parameter #1 of Gui.List.Prototype.Add requires an Array, but received a ComObject.
Source:	Gui.List.Prototype.Add

I have a drop down list that exists in my base thread.

I have a worker that is trying to to call Add() on the drop down list in the base thread.

I receive the error above that states the array I am attempting to pass to the drop down list via Add() is a ComObject, not an array.

The array is most certainly an array, which I have verified using type().

**Comment by thqby** [comment]
ahk objects are not designed for multithreading, so when passed through threads they are encapsulated as com objects for secure access.

You need to convert it to the corresponding ahk object in another thread, such as `[array_as_comobj*]`.

**Comment by Clamsoda** [comment]
Understood,

Thank you for the insight.
