### ISSUE TITLE
Implementation of ResGet

### ISSUE THREAD

**Issue by Clamsoda** [thqby/AutoHotkey_H#48]
Is there a comparable implementation of ResGet() from HotKeyIt's AHK_H and AHK_H v2?

See:
https://hotkeyit.github.io/v2/docs/commands/ResGet.htm

**Comment by thqby** [comment]
https://github.com/HotKeyIt/ahkdll-v2-release/blob/master/Compiler/v2/lib/ResGet.ahk

**Comment by Clamsoda** [comment]
Any plans to implement this natively, instead of having to use an exported function from the DLL?

Thank you.

**Comment by thqby** [comment]
This functionality can be implemented with simple ahk code without high performance requirements.
