### ISSUE TITLE
[功能] 更新UnZip/Zip()底层

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#49]
能更新解压缩函数的底层库吗？比如用这个 https://github.com/zlib-ng/zlib-ng

解压缩函数非常有用，解压gzip数据，快速查看zip文件信息，解压文件到内存，都是常用的需求。不过不知道为啥这些函数性能很低，有时比用7Z命令行都要慢，而且经常出错，有时还崩溃。渐渐我就不用了。如果能用zlib-ng这样的新库重新实现就好了。刚测试了下zlib-ng.dll的调用，似乎也并不复杂。

**Comment by thqby** [comment]
怎么出错？

**Comment by Frozen1084** [comment]
错误很常见，我记得最后遇到的错误是一个gzip.dll可以正常解压的gzip数据，用内置函数解压就报错。作为一个http库的gzip解压方法，内置函数解压一直正常，不知道为何遇到这gzip数据就报错，这导致我弃用了那个http库 = =，因为gzip.dll只有32位，我找不到替代方法

**Comment by thqby** [comment]
修补了点zip函数的bug，跟压缩gzip有关

**Comment by thqby** [comment]
高版本系统内置了gzip
https://github.com/thqby/ahk2_lib/blob/master/gzip.ahk

**Comment by Frozen1084** [comment]
谢谢，请问这个库有方法检测文件是否加密以及密码是否有效吗？

我遇到的问题都是解压函数。

**Comment by thqby** [comment]
gzip是不支持密码的, 带密码的zip能正常读取，密码错了会有错误信息，读取特殊的几个格式需要额外调用相应的函数。

>我遇到的问题都是解压函数。

可能和实现有关，当前没有首先识别数据头，先按zip解，不对再读gzip数据头，可能就会误读或多读。
还有网络请求中的gzip，一些实现自带解码的

**Comment by Frozen1084** [comment]
我在gzip的解压上不涉及加密，仅仅是单纯解压出错。那两句话不相关。

这个库是支持密码解码的，Window 11 支持rar/7Z 就是使用它。我说的是rar/7z的密码解密。
相关函数：
archive_read_set_passphrase_callback
archive_read_add_passphrase

现在用脚本解密，必须用7z.exe不断命令行尝试，要是archive.dll能够解密可真解决大难题了。

这个库的官方项目：
https://github.com/libarchive/libarchive

**Comment by Frozen1084** [comment]
大家在最新的WIN11测试，发现也无法解密，是这个库本身的缺陷

**Comment by thqby** [comment]
部分格式支持加解密, zip的aes和zipcrypto两种加密方式测试了没问题。
