### ISSUE TITLE
release 无法编译

### ISSUE THREAD

**Issue by DeepTulip** [thqby/AutoHotkey_H#52]
LINK : error C2220: 以下警告被视为错误
LINK : warning C4727: 具有相同时间戳的名为 D:\autohotkey_h-alpha\temp\x64\release\autohotkey64.pch 的 PCH 已存在于 D:\autohotkey_h-alpha\temp\x64\release\pch_min.obj 和 D:\autohotkey_h-alpha\temp\x64\release\pch.obj 中。 使用第一个 PCH。
  正在创建库 D:\AutoHotkey_H-alpha\bin_minimal\AutoHotkey64.lib 和对象 D:\AutoHotkey_H-alpha\bin_minimal\AutoHotkey64.exp
正在生成代码
Previous IPDB not found, fall back to full compilation.
All 3471 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
LINK : fatal error LNK1257: 代码生成失败
已完成生成项目“AutoHotkeyx.vcxproj”的操作 - 失败。
========== 生成: 3 成功，1 失败，2 最新，0 已跳过 ==========

MT 版本正常

**Comment by thqby** [comment]
直接git clone, 然后编译release没有显示以上错误

**Comment by DeepTulip** [comment]
找到原因了，是我只复制了 lib_mpir 64 的关系，没有想到缺失 32 位会对 64位的编译有影响。
