### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by Clamsoda** [thqby/AutoHotkey_H#53]
Can you provide a working example of the Alias function?  No matter what I try, it does not work.

Thank you.

**Comment by thqby** [comment]
```
aa := 2
Alias(bb := 0, aa) ; Alias('bb', aa)
MsgBox aa ' ' bb
bb := 1
MsgBox aa ' ' bb
```

**Comment by Clamsoda** [comment]
It still does not work for a variable in another thread.

```autoit
TestThread := Worker("
(
	Persistent(true)

	TestVar := "Test"
)", , "TestThread")

MsgBox(TestThread["TestVar"]) ; "Test"

Alias(bb := 0, TestThread["TestVar"])

MsgBox(bb) ; ""
```

**Comment by thqby** [comment]
```
#DllImport ahkGetVar, ahkGetVar, t==siui
TestThread := Worker("
(
	Persistent(true)

	TestVar := "Test"
)", , "TestThread")

Alias(bb := 0, ahkGetVar('TestVar', 1, TestThread.ThreadID))

MsgBox(bb)
```

~This is not designed for multithreading, so it may cause the program to crash.~
This is used in multithreading and can cause the program to crash.

**Comment by Clamsoda** [comment]
I see.

It was my impression that the _purpose_ of Alias() was for aliasing variables from other threads; at least the documentation on the original AHK_H v2 seems to imply that.

What is the intended use case for Alias()?

Thank you.

**Comment by thqby** [comment]
- Passing a user function object to another thread in this way may not work properly.
- Read and write numeric types that should raise no exceptions.
- When thread synchronization mechanisms such as critical sections are not used, multiple threads read and write string and object types, which may cause program crash.

```
#DllImport ahkGetVar, ahkGetVar, t==siui
TestThread := Worker("
(
	Persistent(true)
	a := 1
	TestVar := "Test"
	while a
		continue
	loop 1000
		TestVar .= 'b'
	until a
)", , "TestThread")

Alias(bb := 0, ahkGetVar('TestVar', 1, TestThread.ThreadID))
TestThread['a'] := 0
loop 1000
	bb .= 'a'
TestThread['a'] := 1
MsgBox(bb)
```
If you run this script multiple times, there is a high probability that it will crash.

**Comment by Clamsoda** [comment]
Thank you for taking the time to explain.
