### ISSUE TITLE
AutoHotkey gui 干扰窗口

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#57]
Window窗口有个错误显示现象。举个例子，有两个窗口 A 和 B，A是300*300那样大小的小窗口，B是最大化的大窗口。当A在激活时，你用鼠标点击了B，那么B激活，当前的窗口顺序是B1，A2。如果这时你创建并激活了一个新窗口-C(比如用AutoHotkey热键创建了一个窗口)，那么当前的窗口顺序就是 C1 B2 A3。
现在问题来了，如果你关闭了C窗口，很大机率后续激活的不是B，而是A。也就是说你无法正确地回到上一个窗口。
后来我发现，这个问题只出现在C窗口是AutoHotkey窗口时，关闭激活的任何其他窗口都没有这个问题。于是我测试下来，发现有时候AutoHotkey窗口可以100%重现这个问题，但很少情况下又重现不了，不可捉摸的触发条件。
而且这似乎也不是AutoHotkey窗口关闭时产生的现象，因为我测试强制杀进程的方法让AutoHotkey来不及响应关闭事件，问题仍旧存在。也就是说，造成窗口次序混乱的问题可能是在AutoHotkeyGUI创建时出现的。

为了避免这个问题，我删除了所有AutoHotkey GUI脚本，转而用WINAPI自写GUI，这个问题就再也没有出现过了。

**Comment by thqby** [comment]
使用L版测试也这样吗

**Comment by Frozen1084** [comment]
不好意思，不知道是因为我的电脑环境变化，还是最近的更新，我试了一个小时也没重现这个问题。
