### ISSUE TITLE
COM interface class name

### ISSUE THREAD

**Issue by lstrfwp** [thqby/AutoHotkey_H#59]
The class name shows `AuotHotkey2`. Is it intentional or a misspelling?
```
ahk2 := ComObject("AutoHotkey2.Script")
MsgBox Type(ahk2)
```

**Comment by thqby** [comment]
Expect `AutoHotkey2.Script`?

**Comment by lstrfwp** [comment]
`AutoHotkey2` instead of `AuotHotkey2`

**Comment by thqby** [comment]
it is misspelling.
