### ISSUE TITLE
`.Get()` fails when used with `__Call()`.

### ISSUE THREAD

**Issue by anonymous1184** [thqby/AutoHotkey_H#61]
When dynamically calling a `.Get()` method, fails with:

```
Too few parameters passed to function.
     Specifically: Object.Prototype.Get
```

Example:

```ahk
test := Example()
test.Set() ; Works
test.Get() ; Doesn't work

class Example {

    __Call(Method, *) {
        OutputDebug(Method)
    }

}

```

**Comment by thqby** [comment]
After ahk_h v2.0.2, object, like array and map, also has a `Get` method.

**Comment by anonymous1184** [comment]
Just saw that in the [ea7a4a1][1] commit. I guess I should have been using a previous build, because it wasn't failing until today I upgraded to v2.0.3, then again after I reverted (but with the latest v2.0.2).

So much to thank you for, specially the JSON5 support... that's amazing.

And I guess you can close the issue (specially since isn't an issue *per se*, just me missing the reference in the README.md).

[1]: https://github.com/thqby/AutoHotkey_H/commit/ea7a4a16755f89101ddccd51505e6178e6cc3a15
