### ISSUE TITLE
v2.0.3 keeps crashing

### ISSUE THREAD

**Issue by anonymous1184** [thqby/AutoHotkey_H#62]
I've been running the same\* script for quite some time now, previous v2.0.x didn't crash but v2.0.3 keeps randomly crashing.

<sup>_With small updates here and there to hotkeys or hotstrings_</sup>

I really haven't been able to replicate, but I put the script to run in a `loop`:

```cpp
loop {
    exe := "C:\Program Files\AutoHotkey\H2\AutoHotkey64_UIA.exe"
    dir := "D:\AHK\Scripts\main"
    script := dir "\main.ahk"
    exitCode := RunWait(exe ' "' script '"', dir)
    MsgBox(Format("Exit code: {} (0x{:X})", exitCode, exitCode & 0xFFFFFFFF), , 0x40010)
}
```

To grab the exit code and see if something in specific trigger the crash. So far I haven't been able to make it consistent, but the error is always the same:

```
-1073740940 (0xC0000374)
```

Also, just by selecting `Exit` from the tray icon, it crashes with the same error rather than properly exit.

---

I need the script to run with UI Access, so I have always signed the executables and never had issues before, thus I don't think that might be the issue. My current method of signing is with PowerShell's `Set-AuthenticodeSignature` if that matters.

All the references from that particular error code are for heap corruption or some form of memory allocation. Perhaps that can help narrow down against the changes from v2.0.2 to v2.0.3

As always, thanks for your time.

**Comment by thqby** [comment]
what is main.ahk?

**Comment by anonymous1184** [comment]
My main v2.0 script that I've been running since January this year.

**Comment by thqby** [comment]
I need a script that reproduces the issue.

**Comment by anonymous1184** [comment]
Given that is my main script is quite big, so I started trimming down, removing one lib at a time. Until it was basically just a few functions, then I kept pushing to try and pin down the culprit.

Turns out that even if I had written the function a few months ago, I wasn't really using it until I updated to v2.0.3 and started reading a JSON5 file instead of a JSON and formatting some values from the file.

```ahk
len := GetNumberFormat(LOCALE_USER_DEFAULT, 0, str, 0, 0, 0)
buf := Buffer(len, 0) ; <--- This caused the issue
len := GetNumberFormat(LOCALE_USER_DEFAULT, 0, str, 0, buf.Ptr, buf.Size)
```

The return value for [`GetNumberFormat()`][1] is a count of `TCHAR`, so I should have multiplied by 2 because the buffer must be big enough for a wide string (UTF-16LE).

It does not raise `A_LastError` and it returns the expected value, so I wasn't aware of any issues. I guess after some garbage collection or when the thread finishes, a heap is left corrupted and eventually the thread dies and so it crashes.

If you wish the code to replicate this issue (in my case it was in a timer thread), I can create a test case. Sorry if I didn't exhaust all my resources before posting, but I really thought it was on AHK side and not on mine.

You can close this, or if you can provide a guard for heap corruption when trying to write more data than allocated (I don't know if it is possible), you might want to reference this issue.

Thanks again!

[1]: https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getnumberformatw

**Comment by thqby** [comment]
>  if you can provide a guard for heap corruption when trying to write more data than allocated 

Write operations that occur inside winapi are uncontrollable.
