### ISSUE TITLE
`Worker` changes `A_WorkingDir`

### ISSUE THREAD

**Issue by anonymous1184** [thqby/AutoHotkey_H#66]
As soon as a `Worker` is created, the value of `A_WorkingDir` is changed, moreover it doesn't change the value when finished.

![image](https://github.com/thqby/AutoHotkey_H/assets/53758552/ee62decf-356a-47a7-9050-1219015e05c5)

I think a worker thread should not change the parent thread working directory.

Code to reproduce:

```ahk
#Requires AutoHotkey_H v2.0

SetWorkingDir(A_ScriptDir)

OutputDebug("Start: " A_WorkingDir "`n")

SetTimer(WhereAmI, 10)
w := Worker("
(
    #NoTrayIcon
    Persistent(true)
    ExitIn(ms) => (Sleep(ms), ExitApp())
)")
w.AsyncCall("ExitIn", 1000)
w.Wait()
SetTimer(WhereAmI, 0)

OutputDebug("End: " A_WorkingDir "`n")

ExitApp()

WhereAmI() => OutputDebug(A_WorkingDir "`n")
```

On a seemingly related note, perhaps might be a good idea to have `#NoTrayIcon` and `Persistent(true)` as defaults for threads?

Thanks in advance!

**Comment by thqby** [comment]
The Working directory is process related. Changing it in one thread will affect other threads. The current situation should be broken in this version.

> On a seemingly related note, perhaps might be a good idea to have #NoTrayIcon and Persistent(true) as defaults for threads?

I think it's best to be consistent with other scripts.

**Comment by anonymous1184** [comment]
> The current situation should be broken in this version.

Does that mean it will be fixed in the next release?

> I think it's best to be consistent with other scripts.

Me too, hence the comment... if a script already has a tray icon, why a thread will put another? Apps don't create a tray icon per-thread.

As for the `Persistent(true)`, I found a way to make a thread stick without it, so I guess this one can be optional. Still, it is hard to guess that from the start.

Speaking of hard-to-guess, what does the `Cmd` parameter does in the `Worker` constructor?

**Comment by thqby** [comment]
> Speaking of hard-to-guess, what does the `Cmd` parameter does in the `Worker` constructor?

it's same as [Passing Command Line Parameters to a Script](https://www.autohotkey.com/docs/v2/Scripts.htm#cmd).
