### ISSUE TITLE
object 添加 .has() 方法

### ISSUE THREAD

**Issue by DeepTulip** [thqby/AutoHotkey_H#67]
请问能否给 object 添加 .has() 方法？
因为 obj 支持引号键，现在 V2 也可以像 V1那样自由地使用对象了。我想写个函数来实现 obj["a",1,"t"] 式的使用方法，发现map/arr都有has()函数，只有obj需要进行额外的判断，以使用 HasOwnProp()。如果给 object 添加 .has() 方法，所有对象的判断方法就统一了。

**Comment by thqby** [comment]
object.prototype.has:=object.prototype.hasownprop

**Comment by DeepTulip** [comment]
判断 has 是否映射到 HasOwnProp()，和判断对象是 obj 没什么差别吧。

**Comment by thqby** [comment]
执行上面这句，obj就有has了，不用额外判断

**Comment by DeepTulip** [comment]
我说的"判断"，判断是这行的使用条件。我请求的是无条件的内置，你的方法怎么才能无视条件？
用在"#InitExec"？那要加在所有脚本上。
用在static？static 好像只能在局部环境

**Comment by DeepTulip** [comment]
你就说怎么不需要判断就无条件生效吧。总不能在所有用 has()的上方加上这行代码吧

**Comment by thqby** [comment]
随便那个文件加一句`#InitExec object.prototype.has:=object.prototype.hasownprop`就行
或者编译到ahk.exe的`#2`资源
![image](https://github.com/thqby/AutoHotkey_H/assets/28240311/0794600b-09a0-4c6a-9877-d3e010513061)

**Comment by DeepTulip** [comment]
我有近千个独立的脚本，想要模仿内置，方法1显然需要在所有脚本都添加上，否则同样有近千个lib文件就需要每个都初始化一次。
方法2，不如修改源码自己编译。

我发帖的目的是寻求统一所有对象的.has()方法是否有合理性，并不是我不知道将 HasOwnProp 写到 has()。

**Comment by thqby** [comment]
obj有hasprop和hasownprop，has对应那个还是需求者自己搞吧

**Comment by DeepTulip** [comment]
好的，可能需求不合理吧。
顺带一提，release编译错误，MT和DEBUG正常。

LINK : error C2220: 以下警告被视为错误
LINK : warning C4727: 具有相同时间戳的名为 D:\autohotkey1\autohotkey_h-alpha\temp\x64\releasedll\autohotkey64.pch 的 PCH 已存在于 D:\autohotkey1\autohotkey_h-alpha\temp\x64\releasedll\pch_min.obj 和 D:\autohotkey1\autohotkey_h-alpha\temp\x64\releasedll\pch.obj 中。 使用第一个 PCH。
  正在创建库 D:\AutoHotkey1\AutoHotkey_H-alpha\bin_minimal\AutoHotkey64.lib 和对象 D:\AutoHotkey1\AutoHotkey_H-alpha\bin_minimal\AutoHotkey64.exp

**Comment by thqby** [comment]
最新的？没遇到过

目录不对应，重新生成呢

**Comment by DeepTulip** [comment]
最新的。重新生成或者全新解压的源代码都如此。

**Comment by thqby** [comment]
刚试了，git clone, 打开编译release没问题

**Comment by DeepTulip** [comment]
releases确实正常。之前我一直是直接下载的库压缩包，二者看来有不同
