### ISSUE TITLE
Does this support encrypt with a password like ahkdll does?

### ISSUE THREAD

**Issue by fznhq** [thqby/AutoHotkey_H#70]
If supported, is it necessary to build it myself to change the passwords like ahkdll ?

**Comment by thqby** [comment]
https://github.com/thqby/AutoHotkey_H/blob/5d2ffc618832496e5c406cfc034956a825795f3e/source/globaldata.h#L334

Modify this.

**Comment by fznhq** [comment]
Just asking, with ahkdll it need change so many thing <[here the topic](https://www.autohotkey.com/boards/viewtopic.php?f=65&t=62308)> but with this code i only need change that 1 line ? and one more question, how to compile to exe using this ahk i tried compiled it using [ahkdll v2 release](https://github.com/HotKeyIt/ahkdll-v2-release) is that the correct way ? or there is another way to do that ?

Thanks

**Comment by thqby** [comment]
Only this line. If you have vs2022 and git installed, just git clone the repository, open the sln file, switch to release, and compile

**Comment by fznhq** [comment]
Sorry, maybe you misunderstood. What i mean is how about compiler ahk2exe, where to get that for this ahk ?, or i can just use from [compiler](https://github.com/HotKeyIt/ahkdll-v2-release/tree/master/Compiler) ahkdll ?

**Comment by thqby** [comment]
sure. or [Ahk2Exe_h.zip](https://github.com/thqby/AutoHotkey_H/files/12549807/Ahk2Exe_h.zip)

**Comment by fznhq** [comment]
Thanks for the answer, now everything is clear, im closing this issue
