### ISSUE TITLE
Error with default parameters using `A_*` globals.

### ISSUE THREAD

**Issue by anonymous1184** [thqby/AutoHotkey_H#71]
Any function that uses a global as default parameter, gets an unassigned error:

```ahk
Test()
Test(Param := A_AhkVersion) => MsgBox(Param)
```

I know there are other ways around the issue:

```ahk
Test()
Test(Param?) => MsgBox(Param ?? A_AhkVersion)
```

But I came across that in another user's code that works on the official release.

**Comment by thqby** [comment]
broken by v2.0.5
