### ISSUE TITLE
Critical Error: Function recursion limit exceeded.

### ISSUE THREAD

**Issue by edwyn-amador** [thqby/AutoHotkey_H#73]
Hello, since v2.0.5 to the most recent version (v.2.0.8) ImagePut library is not working anymore (https://github.com/iseahound/ImagePut)

It is throwing the following error

![image](https://github.com/thqby/AutoHotkey_H/assets/36249854/d89163ab-3336-4614-a5f6-c9ebb9f9e1e2)

However, with Lexikos versions still working without issues, can you please solve this issue?

Here it is a sample code:

Sample.ahk:

> #include ImagePut.ahk ; ImagePut v1.10
> #singleinstance force
> 
> ; This script runs on both AutoHotkey v1 and v2.
> hwnd := ImagePutWindow("https://picsum.photos/500", "Thank you for trying ImagePut ♥")
> 
> ; Copy to the clipboard.
> clip := ImagePutClipboard("https://picsum.photos/500")
> 
> ; Save images.
> file1 := ImagePutFile(hwnd)
> file2 := ImagePutFile(clip)

 Thanks.

**Comment by thqby** [comment]
imageput.get conflicts with the existing object.prototype.get

**Comment by edwyn-amador** [comment]
> imageput.get conflicts with the existing object.prototype.get

I see, is that something you can fix in order to not conflict with that library?

This is a crucial library for my script to be used under the autohotkey dll version.

Also is there any workaround in order to get it working for now?

Thanks @thqby

**Comment by anonymous1184** [comment]
@edwyn-amador See #61. What needs to change is the library, in my case I defined the `Get()` method causing the issue in the sub-class functor:

```cpp

    class Functor {

        /* _H v2.0.2 adds Object.Prototype.Get() breaking
        GET verb's dynamic call. This is a workaround. */
        GET(Parameters*) {
            return this.Request("GET", Parameters*)
        }

        __Call(Method, Parameters) {
            return this.Request(Method, Parameters*)
        }

    }
```

You can update the lib and create a PR or raise the issue in the `ImagePut` repo and perhaps the owner will update the lib.

**Comment by edwyn-amador** [comment]
@anonymous1184 Thanks for the insight, unfortunately I am not sure what to modify in the library in order to get it working.

Also I think the ideal fix would be to implement something on this ahk_h version in order to not conflict with other libraries keeping all scripts compatible (at last as much as possible) with the original ahk lexikos with the advantage of having all those extra functionalities with ahk_h, I wish this could be possible.

**Comment by thqby** [comment]
object.prototype.get is the method, `a:={},a.get:=val`, this code will not work.
So, I changed it to a value property, and now the issue arises.
You can solve this issue by changing `get` to another name.

**Comment by anonymous1184** [comment]
> the ideal fix would be to implement something on this ahk_h version

Not quite, this is different from AHK_L, it is a superset to address shortcomings in the official build. So both have a use case:

- AHK_L: Official build, meant for compatibility across the board.
- AHK_H: Superset of AHK_L with extra features, some of them conflict with the vanilla version.

Until the last update, the README had the changes separated (now they are in a big list), still this breaking change is properly acknowledged (in v2.0.2):

> - Added `Object.Prototype.Get(Prop [, Default])`

https://github.com/thqby/AutoHotkey_H/blob/0d98dba77c6c65c506608a0a44c1a7cb5a943f0f/README.md

That is a feature that explicitly clashes with AHK_L, the only way to make it compatible is to remove it. Not having the extra/different features in AHK_H would be just like using AHK_L.

---

I guess I can take a look at the lib. Providing compatibility layers for most of the features is not that hard, please create an issue in the lib repo and tag me.

**Comment by thqby** [comment]
```
class obj {
	static get2:={}
}
class obj2 extends obj {
	static get2(*) {
	}
}
MsgBox obj2.get2 == obj.get2	; 1
MsgBox obj2.GetOwnPropDesc('get2').call == obj2.get2	; 0
class obj3 {
	static get2() {
	}
}
class obj4 extends obj3 {
	static get2(*) {
	}
}
MsgBox obj3.get2 == obj4.get2	; 0
```
This is the code that reflects this issue.

**Comment by anonymous1184** [comment]
The issue (recursion) seems to be solved by either renaming the method:

```diff
diff --git a/ImagePut.ahk b/ImagePut.ahk
index dba914c..c6ec83e 100644
--- a/ImagePut.ahk
+++ b/ImagePut.ahk
@@ -245 +245 @@ class ImagePut {
-   static get(name, p*) {
+   static got(name, p*) {
@@ -282 +282 @@ class ImagePut {
-      keywords := {base: {__get: this.get}}
+      keywords := {base: {__get: this.got}}
@@ -291 +291 @@ class ImagePut {
-         keywords.base := {__get: this.get}
+         keywords.base := {__get: this.got}
@@ -300 +300 @@ class ImagePut {
-            keywords.base := {__get: this.get}
+            keywords.base := {__get: this.got}
@@ -440 +440 @@ class ImagePut {
-      (!k) && k := {base: {__get: this.get}}
+      (!k) && k := {base: {__get: this.got}}
@@ -617 +617 @@ class ImagePut {
-      (!k) && k := {base: {__get: this.get}}
+      (!k) && k := {base: {__get: this.got}}
```

Or explicitly pass the object as argument rather than using `this`:

```diff
diff --git a/ImagePut.ahk b/ImagePut.ahk
index dba914c..ce95e3f 100644
--- a/ImagePut.ahk
+++ b/ImagePut.ahk
@@ -245,2 +245,2 @@ class ImagePut {
-   static get(name, p*) {
-      return ObjHasOwnProp(this, name) ? this.name : ""
+   static get(self, name) {
+      return ObjHasOwnProp(self, name) ? self.%name% : ""
@@ -282 +282 @@ class ImagePut {
-      keywords := {base: {__get: this.get}}
+      keywords := {base: {__get: (self, Name, *) => this.get(self, Name)}}
@@ -291 +291 @@ class ImagePut {
-         keywords.base := {__get: this.get}
+         keywords.base := {__get: (self, Name, *) => this.get(self, Name)}
@@ -300 +300 @@ class ImagePut {
-            keywords.base := {__get: this.get}
+            keywords.base := {__get: (self, Name, *) => this.get(self, Name)}
@@ -440 +440 @@ class ImagePut {
-      (!k) && k := {base: {__get: this.get}}
+      (!k) && k := {base: {__get: (self, Name, *) => this.get(self, Name)}}
@@ -617 +617 @@ class ImagePut {
-      (!k) && k := {base: {__get: this.get}}
+      (!k) && k := {base: {__get: (self, Name, *) => this.get(self, Name)}}
```

**Comment by edwyn-amador** [comment]
Thanks @thqby and @anonymous1184 that solved the issue!
