### ISSUE TITLE
how to share variable between threads

### ISSUE THREAD

**Issue by iAttaquer** [thqby/AutoHotkey_H#74]
How to share variable between threads since you removed critical object. Can you give me some example how to do this?

**Comment by thqby** [comment]
When variables store numeric types, `Alias` can be used to associate variables from two threads.
or 
```
t := Worker(...)
MsgBox t[varname]
```

**Comment by iAttaquer** [comment]
Ok, i trying alias
```
#Requires AutoHotkey v2.0

myvar:=50
Alias("newvar", getvar(myvar))
Script:="
(
    MsgBox myvar
)"
t:=NewThread(Script)
MsgBox "end"
```
but i got this: 
Warning: This variable appears to never be assigned a value.

Specifically: global myvar

▶	001: MsgBox(myvar)

**Comment by thqby** [comment]
```
myvar:=50

Script := "
(
	Alias(myvar:=0, ahkGetVar('myvar', 1, A_MainThreadID))
    MsgBox myvar
)"
t:=NewThread(Script)
MsgBox "end"
```

```
myvar := 50

Script := "
(
	MsgBox Worker(A_MainThreadID)['myvar']
)"
Worker(Script)
MsgBox "end"
```

**Comment by iAttaquer** [comment]
Now i understand, thanks for your help
