### ISSUE TITLE
2.1 是否有可能将函数复制到子线程？

### ISSUE THREAD

**Issue by DeepTulip** [thqby/AutoHotkey_H#78]
现在想要在子线程使用父线程的函数，需要想办法找到父线程的代码，然后正则提取。
请问在2.1 是否有可能将函数复制到子线程？不是调用父线程函数，是将函数复制过来，跳过从脚本解析到函数的过程。
这种复制似乎也与模块化有些关联(瞎猜，我是不懂C这块)

NewThread("test()",,,test)
test() => MsgBox(A_ThreadID)

**Comment by thqby** [comment]
太难了，函数可能引用其他用户函数，而且没有函数的克隆方法

如果只是调用可以将调用请求发回主线程，下面代码会显示主线程线程id
`NewThread('worker(0)["test"]()')`

**Comment by DeepTulip** [comment]
那么是否有可能从函数获取代码呢？比如 test.ToCode()

**Comment by thqby** [comment]
为什么不用#include

**Comment by DeepTulip** [comment]
#include 不适合所有场景，不是所有函数都适合保存到 LIB。OK，结束这个话题。
