### ISSUE TITLE
dllcall str 增加 ustr 方法

### ISSUE THREAD

**Issue by DeepTulip** [thqby/AutoHotkey_H#81]
现在很多 dll 的字符串参数都只支持 utf-8，这在调用时通常需要进行类似 "ptr", strbuf(st) 的转换。
那么为 dll 字符串增加一个 ustr 方法是否可能，或者说是否合理？
如果可以实现，真的会节省很多步骤。

啊对了，有个类似的地方，NewThread() 能否添加也添加一个 utf-8 方法，比如 NewThread_utf8()。NewThread 的 3 个参数都是 utf-16，在字符串默认 utf-8类型的语言调用 AutoHotkey.dll 就变得非常繁琐。

**Comment by thqby** [comment]
v2.1可以使用自定义类型
```
class u8str {
    ptr : uptr
    __value {
        get => StrGet(this, 'utf-8')
        set {
                this._buf := buf := Buffer(StrPut(Value, 'utf-8'))
                StrPut(Value, buf, 'utf-8')
                this.ptr := buf.Ptr
        }
    }
}
DllCall(..., u8str, 'str')
```

**Comment by DeepTulip** [comment]
谢谢回复。自定义类型和 "ptr", strbuf(st) 比都没有优势。

**Comment by DeepTulip** [comment]
大佬考慮下唄，現在超多

**Comment by thqby** [comment]
加了`ustr`, 还没更新，缩写为ustr是否合理？

**Comment by DeepTulip** [comment]
astr wstr ustr 似乎不突兀。或者直接使用 "utf8"？更直观

**Comment by thqby** [comment]
utf8字符串类型名为`u8str`，命名风格跟astr,wstr一样，c++中的utf8字符串是std::u8string
