### ISSUE TITLE
AsyncCall Invalid Memory Read/Write

### ISSUE THREAD

**Issue by Clamsoda** [thqby/AutoHotkey_H#83]
I am re-visiting some old code that used to be stable some releases ago.  On current releases, I get an invalid memory read/write when I make an async call to a function in another thread.

Not sure what I need to divulge code wise to help, let me know what I can provide.

**Comment by thqby** [comment]
Provide code that can reproduce this issue.

**Comment by Clamsoda** [comment]
```
Persistent(true)

TestFunction(*) {
	MsgBox("test")
}

TestCode := Worker("
(
	BaseThread := Worker(0)
	BaseThread.AsyncCall("TestFunction")

)")
```

![error](https://github.com/thqby/AutoHotkey_H/assets/3506429/af416c56-3755-48b8-b83f-ea8bc9d48614)

TestFunction is called, a message box shows, and once closed the error is produced.
