### ISSUE TITLE
`HasProp` returns 9

### ISSUE THREAD

**Issue by lstrfwp** [thqby/AutoHotkey_H#84]
```
#Requires AutoHotkey_H v2.1-alpha.8

a := {
    b : 1
}

class classA {
    static propB := 1

    class classB {

    }
}

OutputDebug a.HasOwnProp("b")
OutputDebug classA.HasOwnProp("propB")
OutputDebug classA.HasOwnProp("classB")
OutputDebug a.HasProp("b")
OutputDebug classA.HasProp("propB")
OutputDebug classA.HasProp("classB")
```

`classA.HasProp("classB")` returns 9.
What does 9 mean? I thought `HasProp` returns true or false.

**Comment by thqby** [comment]
9 = 8 | 1

- value and get(MaxParams=0): 1
- get: 2
- set: 4
- method: 8

This feature is used in [pyahk](https://github.com/thqby/pyahk/blob/main/__init__.py#L199) for special treatment of dynamic properties
