### ISSUE TITLE
Invalid memory read/write 报错

### ISSUE THREAD

**Issue by DeepTulip** [thqby/AutoHotkey_H#86]
报错内容：
```
Critical Error: Invalid memory read/write.

        467: }
        469: {
▶       469: Return RegExMatch(s, r, &f, p) ? t < 0 ? f : f[t] : ''
        469: }
        471: {

The program is now unstable and will exit.
```
其实就是之前说的 rem_num() 函数。
这个报错的问题是它除了报错之外，没提供其他有用的信息。

这个错误长期存在，我大概1-2个月会遇到一次。也就是说，这段时间同一代码成千上万次的正常运行。
我不可能使用1-2个月的调试版本来捕捉它。我也怀疑在调试环境里这个错误是不是能够触发。
当然，我花了大量时间来寻找代码中可能的错误，但显然这些代码是正常正确的。

我的建议是，即使无法正确报错，也不要随便报错。我第一次遇到这个错误，花费了几个小时尝试在"RegExMatch(s, r, &f, p) ? t < 0 ? f : f[t] : ''" 找错误，最后只觉得受到愚弄。

**Comment by thqby** [comment]
这个错误可能会有潜伏期，在再次访问这段内存时才出现错误，指向的行有时候有用，有时候没用。

**Comment by DeepTulip** [comment]
一个新的报错：

Critical Error: Invalid memory read/write.

▶	004: FileRecycleEmpty()


我忽然意识到一个重要参数，所有出现错误的代码都是用 addScript() 加载的，不是原生代码，这可能是 H 版的独有错误。

**Comment by thqby** [comment]
addScript有出现错误吗

**Comment by DeepTulip** [comment]
没有。我只用 addScript 加载代码，而不调用。调用者是原生代码。

简单来说，新代码可能是：
xxx(){
	rem_num("xxx","xxx") 
}

然后 addScript 将它添加到进程

而调用者可能是一个热键：
比如 f1:: %'xxx'%()

最后，报错的是原生代码里的rem_num() 函数。
