### ISSUE TITLE
class 内的 DynaCall 函数如何等同普通函数？

### ISSUE THREAD

**Issue by DeepTulip** [thqby/AutoHotkey_H#88]
在包装 DLL 类时，我尝试用 DynaCall 代替普通函数，但在调用时，总是会把类本身作为参数添加进去

t.a(A_ScriptHwnd, 5) 会变成 t.a(t, A_ScriptHwnd, 5)

请问 DynaCall 函数如何等同普通函数？

```
t := test()
t.a(A_ScriptHwnd, 5)

class test {

	a := DynaCall("ShowWindow", "i==i6i")

	b(p*) {
		MsgBox p.length
	}
}
```

**Comment by thqby** [comment]
这个就等同普通函数
```
t := test()
t.a(A_ScriptHwnd, 5)
t.c(A_ScriptHwnd, 5)
f(p*) {
	MsgBox p.length
}
class test {

	a := DynaCall("ShowWindow", "i==i6i")
	c := f

	b(p*) {
		MsgBox p.length
	}
}
```

```
test.msg(0, 'aa', 'hi')
test.method(1,2)
test.msg2(0, 'aa', 'hi')
class test {
	static __New() {
		api := DllCall(A_AhkPath '\ahkGetApi', 'cdecl ptr')
		m := ObjFromPtr(ComCall(26, api, 'uint', 13, 'ptr', 0, 'int', 0, 'ptr'))
		NumPut('ptr', NumGet(ObjPtr(m), 'ptr'), ObjPtr(this))
		this.DefineProp('msg2', { call: DynaCall("MessageBoxW", "i==tssui") })
	}
	static msg := DynaCall("MessageBoxW", "i==tssui")
	static method(p*) {
		MsgBox(p.length)
	}
}
```

**Comment by DeepTulip** [comment]
多谢，我想在不失简洁的同时，让 t.a() 等同 t.b()，现在两个方法似乎都不满足。
看到 ahkGetApi 这块，就是我盲区了，大佬真应该出个 ahkGetApi 教程。而且它的调用为何总是被 COM 包装，是为了访问安全吗？COM 虽然好用，但真的低效。

**Comment by thqby** [comment]
COM并不低效，同线程的调用速度几乎与c函数无差，最慢的是跨进程调用的COM组件，其次是需要线程同步的跨线程COM调用。
导出COM接口主要用于第三方调用，能明显减少导出函数的获取。在opencv_ahk和pyahk项目中都有使用这个。

上面的方式在部分情况下并不安全，类对象与`ComCall(26, api, ...)`返回的对象比较，缺少一个ptr大小成员，当访问它时可能指向错误的地址。

**Comment by DeepTulip** [comment]
大佬就出个 ahkGetApi 教程呗。
比如包装 lua.dll，用三种方法比较：1，用 ahkGetApi+COM 包装；2，只用 ahkGetApi 包装；3，都不用，只用普通方法包装。
我看了 pyahk，算是看得懂，但完全不明白原理。

**Comment by DeepTulip** [comment]
这似乎只是单纯的 object 属性的问题。是因为 DynaCall 对象没有 Call？

```
obj := {}
obj.t := DynaCall("ShowWindow", "i==i6i")
MsgBox obj.t(A_ScriptHwnd, 5)
MsgBox obj.t.HasMethod("Call")
```

**Comment by thqby** [comment]
跟这个无关

**Comment by DeepTulip** [comment]
原来只需要这样：

```
obj := {}
obj.t := DynaCall("ShowWindow", "i==i6i")
MsgBox (obj.t)(A_ScriptHwnd, 5)
```

**Comment by thqby** [comment]
或者
```
obj := Map()
obj['t'] := DynaCall("ShowWindow", "i==i6i")
MsgBox obj['t'](A_ScriptHwnd, 5)
```

**Comment by DeepTulip** [comment]
还是放弃了，对比测试下来，DynaCall 保存为单独变量来调用耗时为 1 秒的话， obj.t() 为 1.5 秒，obj["t"\]() 为 2 秒

**Comment by DeepTulip** [comment]
都测试了下，没想到 dllcall() 这么慢啊

测试IsWindow()
	loop 1000000
		DllCall('IsWindow', 'ptr', id, 'int')


dllcall() 0.335195   DllCall('IsWindow', 'ptr', id, 'int')
winapi() 0.198938  IsWindow(id)
DynaCall var 0.205567
DynaCall obj.t() 0.253463
DynaCall obj["t"] 0.360302

**Comment by thqby** [comment]
Native.MDFunc封装应该更快点，Native.Func再快一点，追求速度是无止境的

p := DllCall('GetProcAddress', 'ptr', DllCall('GetModuleHandle', 'str', 'user32', 'ptr'), 'astr', 'IsWindow', 'ptr')
f := Native.MdFunc(p, ['int32', 'intptr'])

**Comment by DeepTulip** [comment]
比dllcall 快一倍
没想到快这么多，这种优势完全可以内置啊


dllcall() 0.338767
Native 0.153439
winapi() 0.199968
DynaCallvar 0.201759
DynaCall obj.t() 0.254537
DynaCall obj["t"] 0.367912

**Comment by thqby** [comment]
Native 等同于内置函数，是ahkGetApi里的几个ahk实现
https://github.com/thqby/AutoHotkey_H/blob/alpha-h/source/exports.h#L122

**Comment by DeepTulip** [comment]
DynaCall 无法使用这种技术吗？

**Comment by thqby** [comment]
可以，参数处理方式不一样，会不兼容以前的调用

**Comment by DeepTulip** [comment]
在 25% 性能提升面前，兼容性不是问题，让我重写所有脚本我都愿意

**Comment by thqby** [comment]
在调用用时久的api时，提升就没这么明显了

**Comment by DeepTulip** [comment]
用上MdFunc()了，我准备把所有dll库都重新包装。
唯一的问题是，它的类型没有对标AutoHotkey类型，DynaCall 只是对类型名的简化，转换无压力。
MdFunc的类型，从variant开始就看不懂了，能加上注释吗？

```
static mdtypes := {
			void: 0,
			int8: 1,
			uint8: 2,
			int16: 3,
			uint16: 4,
			int32: 5,
			uint32: 6,
			int64: 7,
			uint64: 8,
			float64: 9,
			float32: 10,
			string: 11,
			object: 12,
			variant: 13,
			bool32: 14,
			resulttype: 15,
			fresult: 16,
			params: 17,
			optional: 0x80,
			retval: 0x81,
			out: 0x82,
			; thiscall,
			uintptr: A_PtrSize = 8 ? 8 : 6,
			intptr: A_PtrSize = 8 ? 7 : 5,
		}
```

如果换成 2.1的类型名是否更直观：

```
	static mdtypes := {
		void: 0,
		i8: 1,
		u8: 2,
		i16: 3,
		u16: 4,
		i32: 5,
		u32: 6,
		i64: 7,
		u64: 8,
		f64: 9,
		f32: 10,
		str: 11,
		object: 12,
		variant: 13,
		bool: 14,
		resulttype: 15,
		fresult: 16,
		params: 17,
		optional: 0x80,
		retval: 0x81,
		out: 0x82,
		; thiscall,
		uintptr: 8,
		intptr: 7,
	}
```

**Comment by DeepTulip** [comment]
大佬 astr 和 wstr 在MdFunc 要怎么写？

**Comment by thqby** [comment]
没有astr， str就是wstr
