### ISSUE TITLE
请教个类包装问题

### ISSUE THREAD

**Issue by DeepTulip** [thqby/AutoHotkey_H#89]
这是 AutoHotkey 常见的类包装方式：

```
a := test_1()
MsgBox a.StrToIntW("123")

class test_1 {
        static __new() {
                t1.StrToInt := DllCall('GetProcAddress', 'ptr', DllCall('GetModuleHandle', 'str', 'shlwapi', 'ptr'), 'astr', 'StrToIntW', 'ptr')
        }

        StrToIntW(st) {
                return DllCall(t1.StrToInt, "str", st, 'int')
        }
}
```

这是我使用mdfunc特性包装的类。创建全局变量，然后赋予给它mdfunc函数。
单纯比较StrToIntW()，它比A方案快了大概8-9倍。

```
b := test_2()
MsgBox test_2_StrToIntW("123")

class test_2 {
	static __new() {
		global
		local ptr := DllCall('GetProcAddress', 'ptr', DllCall('GetModuleHandle', 'str', 'shlwapi', 'ptr'), 'astr', 'StrToIntW', 'ptr')
		local fn := 'test_2_StrToIntW'
		%fn% := Native.mdfunc(ptr, ["int32", "string"])
	}
}

test_2_StrToIntW := 1
```

我本来打算重写几个常用的库，但马上遇到了新问题。
如果主脚本使用 #Include <test_2> 引用，这个方法一切正常。
但如果是间接引用，比如主脚本引用 #Include <test_3>，而 test_3.ahk里引用了 #Include <test_2>，然后在test_3()调用test_2_StrToIntW("123")

```
#Include <test_2>
test_3( ){
static _:= test_2()
MsgBox test_2_StrToIntW("123")
}
```

这时就报错了：

```
Error: This variable has not been assigned a value.

Specifically: global test_2_StrToIntW

▶	004: MsgBox(test_2_StrToIntW("123"))

```

请问大佬这个问题有办法解决吗？

**Comment by thqby** [comment]
- 调整#include顺序
- 使其初始化，`(cls)`
- #InitExec expr

**Comment by DeepTulip** [comment]
谢谢回复，1和2 我都试过，没有解决问题。请问2是什么意思？
#InitExec的问题是它如何也处于lib中，它无法操作全局变量。


完整的测试脚本：
主脚本：
```
#include <xx3>


MsgBox xx2_xx
MsgBox xx3()
```


xx3:
```
#include <xx2>

xx3(){
	static _ := xx2()
	xx2_xx()
	return 2
}

```



xx2:
```
#InitExec xx2_init()

xx2( ){

}


xx2_init(){
	global
	fn:='xx2_xx'
	%fn%:=4
}

xx2_xx:=1
```

**Comment by thqby** [comment]
前面不是用类来初始化全局变量吗？
在类test_3的static __new里加入(test_2)即会初始化test_2

在全局域直接#InitExec xx2_xx := 4
不就好了

**Comment by DeepTulip** [comment]
这个问题的本质是：在#include二次引用的函数内，初始化的全局变量不在主脚本生效。所有不是没init，是init后，主脚本调用读取这个变量报错。

记得我最初的目的是把全局变量作为函数使用吗？所以生成时必然嵌套几层函数。#InitExec xx2_init() 只是对这个环节的模拟。
或者你认为#InitExec xx2_xx := 4生效，#InitExec xx2_init()不生效，不是一个问题？

#InitExec xx2_init()

xx2_init(){
	global
	fn:='xx2_xx'
	%fn%:=4
}

**Comment by thqby** [comment]
如果我没记错#initexec是在当前作用域执行的

**Comment by thqby** [comment]
如果我没记错#initexec是在当前作用域执行的，你可能初始化的是局部变量

**Comment by DeepTulip** [comment]
明白了，看来是调用的ahkExec()。那么 #initexec 不是一个解决方案。

那么回到最初的问题。

1，这个类添加到主脚本可以正常使用。这个类本身是没有错的对吧。
```
class test_2 {
	static __new() {
		global
		local ptr := DllCall('GetProcAddress', 'ptr', DllCall('GetModuleHandle', 'str', 'shlwapi', 'ptr'), 'astr', 'StrToIntW', 'ptr')
		local fn := 'test_2_StrToIntW'
		%fn% := Native.mdfunc(ptr, ["int32", "string"])
	}
}

test_2_StrToIntW := 1
```

2，将它保存到lib，用#Include在主脚本调用也正常。

3，但在主脚本#Include的lib里，再次#Include这个类，并明确地初始化了test_2类，在主脚本读取test_2_StrToIntW就会报错。
请问这是个问题吗？

**Comment by DeepTulip** [comment]
一个完整的重现示例
[bug test.zip](https://github.com/thqby/AutoHotkey_H/files/14957062/bug.test.zip)

**Comment by thqby** [comment]
运行了，没报错

**Comment by DeepTulip** [comment]
试这个

[bug test.zip](https://github.com/thqby/AutoHotkey_H/files/14957292/bug.test.zip)

**Comment by thqby** [comment]
#UseStdLib导致的
