### ISSUE TITLE
关于#DefineDefault[Object/Array/Map]Value

### ISSUE THREAD

**Issue by Frozen1084** [thqby/AutoHotkey_H#9]
请问能否恢复这个命令？

实际上如果"OBJ.Default"有存在的意义，那么它也有存在的价值。比如我所有的map对象都设定了默认值。为此我写了个专门的创建函数：
`newmap( )=> (t:=map(),t.Default:="",t.CaseSense:="off",t)`
它有很大的缺点，无法初始化数据。但这也很大程度减缓了从V1转换到V2的痛苦。

我非常确定即使熟悉V2后，我也会这样使用map。虽然这是不严谨的，但作为非程序员，很多用户只追求简单，尽量减少非必要的报错。大量的报错真的会消耗学习的耐心。

这也能解决在静态变量方面的麻烦：
`static t:=(t:=map(),t.Default:="",t.CaseSense:="off",t[1]:=2,t[3]:=4,t)`

而如果要在V1实现同样的效果，我们知道有多简单。

对很多人来说，#DefineDefault[Object/Array/Map]Value真的是一劳永逸的方法。

---

另外一个问题，这个调用原本在H正常，现在报错说第二个参数无效。
而我在你的版本找不到相关的文档，请问如何修改它？

`MsgBox DynaCall(lib, ["i==twit*t*", 2, 3, 4, 5, 1], 123)`

---
我觉得真的需要一个记录新功能的文档。很多东西似乎只有作者在使用，其他人想使用却找不到使用方法。比如新添加的ahkapi，我一直想知道它是不是可以让我们不加载ahk线程的情况调用内置的函数，让我们可以从其他语言里调用它，类似dllcall("WinActivate",hwnd)。
我在其他语言中有个激活窗口的需求，但一直无法实现AHK同样的效果，我不得不运行一个AHKDLL线程，只为了WinActivatew命令。

**Comment by thqby** [comment]
第一二点在刚上传的版本中已修复
第三点如果只用这一个功能，直接复制这一功能的部分代码就行了。ahkapi有上传使用例子，是用来在外部语言调用ahk对象或者将外部库封装给ahk使用，如opencv_ahk项目；pyahk项目是python从ahk中获取功能并使用，都是在当前线程操作的。
