### ISSUE TITLE
Worker ExitApp 不能正常退出死循环

### ISSUE THREAD

**Issue by Angels-D** [thqby/AutoHotkey_H#93]
``` ahk
work := Worker("
(
    keep := true
    x := 0
    while(keep) {
        Sleep(1000)
        ToolTip(x)
        x := x + 1
    }
)")
F1::work.ExitApp()
F2::work["keep"] := false
```
F1后循环仍然继续，且Sleep(1000)失效
只有通过F2的方法可以正常退出死循环

**Comment by thqby** [comment]
这是故意的，强制退出会内存泄露，进程不结束线程占用的内存将不会释放。

**Comment by Angels-D** [comment]
那除了例子中F2之类的方法，还有更好处理死循环的方法吗

**Comment by thqby** [comment]
work["Thread"]("Terminate", true)
能强制中断循环，如果有需要手动释放的资源，也会内存泄漏

**Comment by changxiaotian** [comment]
> work["Thread"]("Terminate", true) 能强制中断循环，如果有需要手动释放的资源，也会内存泄漏

大佬我用这个案例试了一下，这个terminate也没办法终止循环，我是AutoHotkey v2.1-alpha.10这个版本

**Comment by thqby** [comment]
@changxiaotian alpha.14已修复
