### ISSUE TITLE
程序运行一段时间后 会自动终止，不报错，只显示下面这句话

### ISSUE THREAD

**Issue by six7ths** [thqby/AutoHotkey_H#99]
[Done] [pid:8552] exited with code=3221226525 in 8551.134 seconds

程序是循环和热键，应该永久执行下去，结果i总是随机 终止

用2.018和2.1 a14，都会出这种问题，不报错，不抛出任何Error

**Comment by six7ths** [comment]
搜了一下，可能是vscode的问题，有些人用vscode也会出这个“exited with code=3221226525”。 我再看看怎么复现

**Comment by six7ths** [comment]
刚才又出问题，
[Done] [pid:25116] exited with code=3221226356 in 441.738 seconds

**Comment by six7ths** [comment]
昨天又试了一晚上，没有退出。 感觉，跟vscode插件有关；因为我是用vscode插件， 现在autohotkey v2 language support被ahkplusplus整合进去了，所以两个只能选一个； 好像ahkpp查看方便一些，所以我就昨天早上转了ahkpp，结果可能因为我的ahk_H，用的是ahkv2lp自带的库，没有加进c盘ahk安装目录库里面，所以就出问题了。 昨晚又改回ahkv2lp，测试一晚上，就没再出过这个退出情况。  本周我再多测测，看看什么情况

**Comment by thqby** [comment]
ahkv2lp是什么？
code=3221226356一般在无效的内存读写时出现

**Comment by six7ths** [comment]
就是autohotkey v2 language support 插件的缩写啊，我上面写的太长，就缩写成这个了。

今天上午一个上午，没有再出现 这两种意外exited

**Comment by six7ths** [comment]
又运行了一个晚上，大概9个多小时，没报错。 今天白天再测一天，没问题的话，就是ahkpp的问题了。

**Comment by six7ths** [comment]
测了一个白天，没出这两个异常退出情况， 应该是ahkpp对ahk_H支持不太好的原因吧。 可以close了。

**Comment by RaptorX** [comment]
This error is related to `autohotkey.exe`  not VSCode. I was running into this issue in a loop as well. The program becomes unstable and crashes. I was having the issue with a specific regex inside the loop. Once I modified the regex the issue dissapeared.

It seems like autohotkey is writing into memory in an invalid address or something (in my case) it was happening even if I ran the script from explorer instead of VSCode.

**Comment by six7ths** [comment]
> This error is related to `autohotkey.exe` not VSCode. I was running into this issue in a loop as well. The program becomes unstable and crashes. I was having the issue with a specific regex inside the loop. Once I modified the regex the issue dissapeared.
> 
> It seems like autohotkey is writing into memory in an invalid address or something (in my case) it was happening even if I ran the script from explorer instead of VSCode.

我代码里倒是有正则，但是我用ahkpp插件时，不仅出这个不抛异常的直接exit，而且从其他线程读取global array时，从外部dll调用函数取得数据时，都有概率会抛出异常，搞得我不得不的用try-catch把这些交换数据的地方全都包起来了。

结果 就是，我把vscode插件更换了ahkpp回到ahkv2lsp后，这些问题，都再也没出过。昨天晚上我又开机不关机 测试将近12小时，log文件昨晚5个小时，今早7个小时，一个err都没有，也就是说，不仅没有直接exit，连线程间获取数据和dll获取外部数据，都一个错误没有。

所以，我推测大概率是 vscode ahkpp插件的问题。
